version: "2"
run:
  go: "1.24"
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    goimports:
      local-prefixes:
        - golang.org
        - entgo.io
        - github.com
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
